pipeline {
    agent {
        node {
			label "master"
		    }
	}
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
	}
        stage('Dev') {
            steps {
                sh 'echo bateeee5'
            }
		        post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
	}
        }
    }
